
### TEST ROUTES HERE

POST http://localhost:8000/api/mentees
Content-Type: application/json

{
    "name": "Henrique Pitta Laranjinha",
    "email": "20henriquep@gmail.com",
    "password": "HI",
    "role": "mentee"
}

###

POST http://localhost:8000/api/mentors
Content-Type: application/json

{
    "name": "Vera Carter",
    "email": "vera.carter@example.com",
    "password": "securepassword123",
    "role": "mentor",
    "bio": "Robotics engineer passionate about automation.",
    "skills": ["Python", "ROS", "Embedded Systems"],
    "specialization": "Robotics",
    "availability": ["Monday", "Friday"]
}


###

GET http://localhost:8000/api/mentees

###

DELETE http://localhost:8000/api/mentees

###

POST http://localhost:8000/api/chatbot
Content-Type: application/json

{
    "random": "random message"
}

###

GET http://localhost:8000/api/mentors